// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"


// COMPONENT Scoreboard

lv_obj_t * ui_Scoreboard_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Scoreboard;
    cui_Scoreboard = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Scoreboard, 140);
    lv_obj_set_height(cui_Scoreboard, 120);
    lv_obj_set_x(cui_Scoreboard, 0);
    lv_obj_set_y(cui_Scoreboard, 77);
    lv_obj_set_align(cui_Scoreboard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Scoreboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(cui_Scoreboard, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Scoreboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MP2V218HGST1SPText;
    cui_MP2V218HGST1SPText = lv_label_create(cui_Scoreboard);
    lv_obj_set_width(cui_MP2V218HGST1SPText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MP2V218HGST1SPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_MP2V218HGST1SPText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MP2V218HGST1SPText, "0");
    lv_obj_remove_flag(cui_MP2V218HGST1SPText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(cui_MP2V218HGST1SPText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MP2V218HGST1SPText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MP2V218HGST1SPText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SCOREBOARD_NUM);
    children[UI_COMP_SCOREBOARD_SCOREBOARD] = cui_Scoreboard;
    children[UI_COMP_SCOREBOARD_MP2V218HGST1SPTEXT] = cui_MP2V218HGST1SPText;
    lv_obj_add_event_cb(cui_Scoreboard, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Scoreboard, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Scoreboard_create_hook(cui_Scoreboard);
    return cui_Scoreboard;
}

