// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#ifndef _UI_COMP_HOLE_COUNT_H
#define _UI_COMP_HOLE_COUNT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Hole Count
#define UI_COMP_HOLE_COUNT_HOLE_COUNT 0
#define UI_COMP_HOLE_COUNT_SP1P9HGSBCSTEXT1 1
#define _UI_COMP_HOLE_COUNT_NUM 2
lv_obj_t * ui_Hole_Count_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
