// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#ifndef _UI_COMP_PLAYER_SCORE_H
#define _UI_COMP_PLAYER_SCORE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Player Score
#define UI_COMP_PLAYER_SCORE_PLAYER_SCORE 0
#define UI_COMP_PLAYER_SCORE_SP1P9HGSPSSTEXT 1
#define _UI_COMP_PLAYER_SCORE_NUM 2
lv_obj_t * ui_Player_Score_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
