// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#ifndef _UI_COMP_SCOREBOARD_H
#define _UI_COMP_SCOREBOARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Scoreboard
#define UI_COMP_SCOREBOARD_SCOREBOARD 0
#define UI_COMP_SCOREBOARD_MP2V218HGST1SPTEXT 1
#define _UI_COMP_SCOREBOARD_NUM 2
lv_obj_t * ui_Scoreboard_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
