// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"


// COMPONENT MP1V118HScP1Spinbox1

lv_obj_t * ui_MP1V118HScP1Spinbox1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MP1V118HScP1Spinbox1;
    cui_MP1V118HScP1Spinbox1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_MP1V118HScP1Spinbox1, 90);
    lv_obj_set_height(cui_MP1V118HScP1Spinbox1, 90);
    lv_obj_set_x(cui_MP1V118HScP1Spinbox1, -721);
    lv_obj_set_y(cui_MP1V118HScP1Spinbox1, 182);
    lv_obj_set_align(cui_MP1V118HScP1Spinbox1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_MP1V118HScP1Spinbox1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(cui_MP1V118HScP1Spinbox1, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_MP1V118HScP1Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MP1V118HScP1SText1;
    cui_MP1V118HScP1SText1 = lv_label_create(cui_MP1V118HScP1Spinbox1);
    lv_obj_set_width(cui_MP1V118HScP1SText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MP1V118HScP1SText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_MP1V118HScP1SText1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MP1V118HScP1SText1, "0");
    lv_obj_remove_flag(cui_MP1V118HScP1SText1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(cui_MP1V118HScP1SText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MP1V118HScP1SText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MP1V118HScP1SText1, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_MP1V118HSCP1SPINBOX1_NUM);
    children[UI_COMP_MP1V118HSCP1SPINBOX1_MP1V118HSCP1SPINBOX1] = cui_MP1V118HScP1Spinbox1;
    children[UI_COMP_MP1V118HSCP1SPINBOX1_MP1V118HSCP1STEXT1] = cui_MP1V118HScP1SText1;
    lv_obj_add_event_cb(cui_MP1V118HScP1Spinbox1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MP1V118HScP1Spinbox1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MP1V118HScP1Spinbox1_create_hook(cui_MP1V118HScP1Spinbox1);
    return cui_MP1V118HScP1Spinbox1;
}

