// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#ifndef _GO_BALL_RASPBERY_PI_UI_COMP_HOOK_H
#define _GO_BALL_RASPBERY_PI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Ball_Count__create_hook(lv_obj_t * comp);
void ui_comp_Hole_Count_create_hook(lv_obj_t * comp);
void ui_comp_Player_Score_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
