// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_MP1V19HScorecard_screen_init(void)
{
    ui_MP1V19HScorecard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MP1V19HScorecard,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScorecard, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScorecard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MP1V19HScorecard, &ui_img_venice_18th_2047x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MP1V19HScorecard, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MP1V19HScorecard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MP1V19HScorecard, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScLogo = lv_img_create(ui_MP1V19HScorecard);
    lv_img_set_src(ui_MP1V19HScLogo, &ui_img_studio_go_ball_logo_300x273_png);
    lv_obj_set_width(ui_MP1V19HScLogo, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_MP1V19HScLogo, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_MP1V19HScLogo, -7);
    lv_obj_set_y(ui_MP1V19HScLogo, -108);
    lv_obj_set_align(ui_MP1V19HScLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_MP1V19HScMMButton = lv_img_create(ui_MP1V19HScorecard);
    lv_img_set_src(ui_MP1V19HScMMButton, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_MP1V19HScMMButton, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_MP1V19HScMMButton, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_MP1V19HScMMButton, -580);
    lv_obj_set_y(ui_MP1V19HScMMButton, -110);
    lv_obj_set_align(ui_MP1V19HScMMButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MP1V19HScMMButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_MP1V19HScMMButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_MP1V19HScMMBText = lv_label_create(ui_MP1V19HScMMButton);
    lv_obj_set_width(ui_MP1V19HScMMBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScMMBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScMMBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScMMBText, "Main\nMenu");
    lv_obj_add_flag(ui_MP1V19HScMMBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_MP1V19HScMMBText,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScMMBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScMMBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MP1V19HScMMBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MP1V19HScMMBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MP1V19HScMMBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScMMBText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScBButton = lv_img_create(ui_MP1V19HScorecard);
    lv_img_set_src(ui_MP1V19HScBButton, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_MP1V19HScBButton, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_MP1V19HScBButton, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_MP1V19HScBButton, 580);
    lv_obj_set_y(ui_MP1V19HScBButton, -110);
    lv_obj_set_align(ui_MP1V19HScBButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MP1V19HScBButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_MP1V19HScBButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_MP1V19HScBBText = lv_label_create(ui_MP1V19HScBButton);
    lv_obj_set_width(ui_MP1V19HScBBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScBBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScBBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScBBText, "Back");
    lv_obj_set_style_text_color(ui_MP1V19HScBBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScBBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MP1V19HScBBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MP1V19HScBBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScBBText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText, -407);
    lv_obj_set_y(ui_MP1V19HScHText, 70);
    lv_obj_set_align(ui_MP1V19HScHText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText, "Hole");
    lv_obj_clear_flag(ui_MP1V19HScHText,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Text = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScP1Text, -440);
    lv_obj_set_y(ui_MP1V19HScP1Text, 135);
    lv_obj_set_align(ui_MP1V19HScP1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1Text, "Player 1");
    lv_obj_clear_flag(ui_MP1V19HScP1Text,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MP1V19HScP1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MP1V19HScP1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1Text, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Text = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScP2Text, -439);
    lv_obj_set_y(ui_MP1V19HScP2Text, 217);
    lv_obj_set_align(ui_MP1V19HScP2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2Text, "Player 2");
    lv_obj_clear_flag(ui_MP1V19HScP2Text,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MP1V19HScP2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MP1V19HScP2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2Text, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText1 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText1, -284);
    lv_obj_set_y(ui_MP1V19HScHText1, 70);
    lv_obj_set_align(ui_MP1V19HScHText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText1, "1");
    lv_obj_clear_flag(ui_MP1V19HScHText1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText2 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText2, -197);
    lv_obj_set_y(ui_MP1V19HScHText2, 70);
    lv_obj_set_align(ui_MP1V19HScHText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText2, "2");
    lv_obj_clear_flag(ui_MP1V19HScHText2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText3 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText3, -110);
    lv_obj_set_y(ui_MP1V19HScHText3, 70);
    lv_obj_set_align(ui_MP1V19HScHText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText3, "3");
    lv_obj_clear_flag(ui_MP1V19HScHText3,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText4 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText4, -23);
    lv_obj_set_y(ui_MP1V19HScHText4, 70);
    lv_obj_set_align(ui_MP1V19HScHText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText4, "4");
    lv_obj_clear_flag(ui_MP1V19HScHText4,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText5 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText5, 64);
    lv_obj_set_y(ui_MP1V19HScHText5, 70);
    lv_obj_set_align(ui_MP1V19HScHText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText5, "5");
    lv_obj_clear_flag(ui_MP1V19HScHText5,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText6 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText6, 151);
    lv_obj_set_y(ui_MP1V19HScHText6, 70);
    lv_obj_set_align(ui_MP1V19HScHText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText6, "6");
    lv_obj_clear_flag(ui_MP1V19HScHText6,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText7 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText7, 238);
    lv_obj_set_y(ui_MP1V19HScHText7, 70);
    lv_obj_set_align(ui_MP1V19HScHText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText7, "7");
    lv_obj_clear_flag(ui_MP1V19HScHText7,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText8 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText8, 325);
    lv_obj_set_y(ui_MP1V19HScHText8, 70);
    lv_obj_set_align(ui_MP1V19HScHText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText8, "8");
    lv_obj_clear_flag(ui_MP1V19HScHText8,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHText9 = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHText9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHText9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHText9, 412);
    lv_obj_set_y(ui_MP1V19HScHText9, 70);
    lv_obj_set_align(ui_MP1V19HScHText9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHText9, "9");
    lv_obj_clear_flag(ui_MP1V19HScHText9,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHText9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHText9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHText9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScHTextF = lv_label_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScHTextF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScHTextF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MP1V19HScHTextF, 499);
    lv_obj_set_y(ui_MP1V19HScHTextF, 70);
    lv_obj_set_align(ui_MP1V19HScHTextF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScHTextF, "F");
    lv_obj_clear_flag(ui_MP1V19HScHTextF,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScHTextF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScHTextF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScHTextF, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox1 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox1, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox1, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox1, -284);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox1, 135);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox1, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText1 = lv_label_create(ui_MP1V19HScP1Spinbox1);
    lv_obj_set_width(ui_MP1V19HScP1SText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText1, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox2 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox2, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox2, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox2, -197);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox2, 135);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox2, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText2 = lv_label_create(ui_MP1V19HScP1Spinbox2);
    lv_obj_set_width(ui_MP1V19HScP1SText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText2, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox3 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox3, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox3, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox3, -110);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox3, 135);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox3,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox3, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText3 = lv_label_create(ui_MP1V19HScP1Spinbox3);
    lv_obj_set_width(ui_MP1V19HScP1SText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText3, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText3,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox4 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox4, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox4, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox4, -23);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox4, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox4,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox4, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText4 = lv_label_create(ui_MP1V19HScP1Spinbox4);
    lv_obj_set_width(ui_MP1V19HScP1SText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText4, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText4,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox5 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox5, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox5, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox5, 64);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox5, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox5,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox5, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText5 = lv_label_create(ui_MP1V19HScP1Spinbox5);
    lv_obj_set_width(ui_MP1V19HScP1SText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText5, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText5,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox6 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox6, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox6, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox6, 151);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox6, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox6,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox6, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText6 = lv_label_create(ui_MP1V19HScP1Spinbox6);
    lv_obj_set_width(ui_MP1V19HScP1SText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText6, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText6,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox7 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox7, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox7, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox7, 238);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox7, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox7,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox7, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText7 = lv_label_create(ui_MP1V19HScP1Spinbox7);
    lv_obj_set_width(ui_MP1V19HScP1SText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText7, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText7,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox8 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox8, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox8, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox8, 325);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox8, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox8,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox8, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText8 = lv_label_create(ui_MP1V19HScP1Spinbox8);
    lv_obj_set_width(ui_MP1V19HScP1SText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText8, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText8,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1Spinbox9 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1Spinbox9, 85);
    lv_obj_set_height(ui_MP1V19HScP1Spinbox9, 80);
    lv_obj_set_x(ui_MP1V19HScP1Spinbox9, 412);
    lv_obj_set_y(ui_MP1V19HScP1Spinbox9, 136);
    lv_obj_set_align(ui_MP1V19HScP1Spinbox9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1Spinbox9,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1Spinbox9, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1Spinbox9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SText9 = lv_label_create(ui_MP1V19HScP1Spinbox9);
    lv_obj_set_width(ui_MP1V19HScP1SText9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1SText9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1SText9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1SText9, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1SText9,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1SText9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1SText9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1SText9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1SpinboxF = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP1SpinboxF, 85);
    lv_obj_set_height(ui_MP1V19HScP1SpinboxF, 80);
    lv_obj_set_x(ui_MP1V19HScP1SpinboxF, 499);
    lv_obj_set_y(ui_MP1V19HScP1SpinboxF, 136);
    lv_obj_set_align(ui_MP1V19HScP1SpinboxF, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP1SpinboxF,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP1SpinboxF, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP1SpinboxF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP1STextF = lv_label_create(ui_MP1V19HScP1SpinboxF);
    lv_obj_set_width(ui_MP1V19HScP1STextF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP1STextF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP1STextF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP1STextF, "0");
    lv_obj_clear_flag(ui_MP1V19HScP1STextF,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP1STextF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP1STextF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP1STextF, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox1 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox1, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox1, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox1, -284);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox1, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox1, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText1 = lv_label_create(ui_MP1V19HScP2Spinbox1);
    lv_obj_set_width(ui_MP1V19HScP2SText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText1, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox2 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox2, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox2, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox2, -197);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox2, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox2, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText2 = lv_label_create(ui_MP1V19HScP2Spinbox2);
    lv_obj_set_width(ui_MP1V19HScP2SText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText2, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox3 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox3, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox3, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox3, -110);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox3, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox3,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox3, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText3 = lv_label_create(ui_MP1V19HScP2Spinbox3);
    lv_obj_set_width(ui_MP1V19HScP2SText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText3, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText3,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox4 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox4, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox4, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox4, -23);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox4, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox4,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox4, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText4 = lv_label_create(ui_MP1V19HScP2Spinbox4);
    lv_obj_set_width(ui_MP1V19HScP2SText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText4, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText4,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox5 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox5, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox5, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox5, 64);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox5, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox5,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox5, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText5 = lv_label_create(ui_MP1V19HScP2Spinbox5);
    lv_obj_set_width(ui_MP1V19HScP2SText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText5, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText5,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox6 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox6, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox6, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox6, 151);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox6, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox6,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox6, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText6 = lv_label_create(ui_MP1V19HScP2Spinbox6);
    lv_obj_set_width(ui_MP1V19HScP2SText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText6, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText6,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox7 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox7, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox7, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox7, 238);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox7, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox7,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox7, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText7 = lv_label_create(ui_MP1V19HScP2Spinbox7);
    lv_obj_set_width(ui_MP1V19HScP2SText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText7, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText7,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox8 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox8, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox8, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox8, 325);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox8, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox8,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox8, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText8 = lv_label_create(ui_MP1V19HScP2Spinbox8);
    lv_obj_set_width(ui_MP1V19HScP2SText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText8, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText8,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2Spinbox9 = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2Spinbox9, 85);
    lv_obj_set_height(ui_MP1V19HScP2Spinbox9, 80);
    lv_obj_set_x(ui_MP1V19HScP2Spinbox9, 412);
    lv_obj_set_y(ui_MP1V19HScP2Spinbox9, 217);
    lv_obj_set_align(ui_MP1V19HScP2Spinbox9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2Spinbox9,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2Spinbox9, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2Spinbox9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SText9 = lv_label_create(ui_MP1V19HScP2Spinbox9);
    lv_obj_set_width(ui_MP1V19HScP2SText9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2SText9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2SText9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2SText9, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2SText9,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2SText9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2SText9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2SText9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2SpinboxF = lv_obj_create(ui_MP1V19HScorecard);
    lv_obj_set_width(ui_MP1V19HScP2SpinboxF, 85);
    lv_obj_set_height(ui_MP1V19HScP2SpinboxF, 80);
    lv_obj_set_x(ui_MP1V19HScP2SpinboxF, 499);
    lv_obj_set_y(ui_MP1V19HScP2SpinboxF, 217);
    lv_obj_set_align(ui_MP1V19HScP2SpinboxF, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MP1V19HScP2SpinboxF,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_MP1V19HScP2SpinboxF, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MP1V19HScP2SpinboxF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MP1V19HScP2STextF = lv_label_create(ui_MP1V19HScP2SpinboxF);
    lv_obj_set_width(ui_MP1V19HScP2STextF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MP1V19HScP2STextF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MP1V19HScP2STextF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MP1V19HScP2STextF, "0");
    lv_obj_clear_flag(ui_MP1V19HScP2STextF,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MP1V19HScP2STextF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MP1V19HScP2STextF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MP1V19HScP2STextF, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MP1V19HScMMBText, ui_event_MP1V19HScMMBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MP1V19HScMMButton, ui_event_MP1V19HScMMButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MP1V19HScBBText, ui_event_MP1V19HScBBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MP1V19HScBButton, ui_event_MP1V19HScBButton, LV_EVENT_ALL, NULL);

}
