// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_Q1P9HGScreen_screen_init(void)
{
    ui_Q1P9HGScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Q1P9HGScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1P9HGScreen, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1P9HGScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Q1P9HGScreen, &ui_img_venice_18th_2560x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Q1P9HGScreen, lv_color_hex(0x00EE49), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Q1P9HGScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Q1P9HGScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSLogo = lv_image_create(ui_Q1P9HGScreen);
    lv_image_set_src(ui_Q1P9HGSLogo, &ui_img_studio_go_ball_logo_350x319_png);
    lv_obj_set_width(ui_Q1P9HGSLogo, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_Q1P9HGSLogo, LV_SIZE_CONTENT);    /// 337
    lv_obj_set_x(ui_Q1P9HGSLogo, -650);
    lv_obj_set_y(ui_Q1P9HGSLogo, 100);
    lv_obj_set_align(ui_Q1P9HGSLogo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1P9HGSFormat = lv_image_create(ui_Q1P9HGScreen);
    lv_image_set_src(ui_Q1P9HGSFormat, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_Q1P9HGSFormat, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Q1P9HGSFormat, LV_SIZE_CONTENT);    /// 287
    lv_obj_set_x(ui_Q1P9HGSFormat, 1050);
    lv_obj_set_y(ui_Q1P9HGSFormat, -155);
    lv_obj_set_align(ui_Q1P9HGSFormat, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSFormat,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1P9HGSFText = lv_label_create(ui_Q1P9HGSFormat);
    lv_obj_set_width(ui_Q1P9HGSFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSFText, "1P\nQuota\n9H");
    lv_obj_remove_flag(ui_Q1P9HGSFText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSFText, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Q1P9HGSFText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSFText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSMMButton = lv_image_create(ui_Q1P9HGScreen);
    lv_image_set_src(ui_Q1P9HGSMMButton, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_Q1P9HGSMMButton, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Q1P9HGSMMButton, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_Q1P9HGSMMButton, -1050);
    lv_obj_set_y(ui_Q1P9HGSMMButton, -155);
    lv_obj_set_align(ui_Q1P9HGSMMButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Q1P9HGSMMButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Q1P9HGSMMButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1P9HGSMMBText = lv_label_create(ui_Q1P9HGSMMButton);
    lv_obj_set_width(ui_Q1P9HGSMMBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSMMBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSMMBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSMMBText, "Main\nMenu");
    lv_obj_add_flag(ui_Q1P9HGSMMBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Q1P9HGSMMBText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSMMBText, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSMMBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Q1P9HGSMMBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Q1P9HGSMMBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Q1P9HGSMMBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSMMBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSBCounter = lv_image_create(ui_Q1P9HGScreen);
    lv_image_set_src(ui_Q1P9HGSBCounter, &ui_img_go_ball_350x319_png);
    lv_obj_set_width(ui_Q1P9HGSBCounter, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_Q1P9HGSBCounter, LV_SIZE_CONTENT);    /// 335
    lv_obj_set_x(ui_Q1P9HGSBCounter, 650);
    lv_obj_set_y(ui_Q1P9HGSBCounter, 100);
    lv_obj_set_align(ui_Q1P9HGSBCounter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSBCounter,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1P9HGSBCText = lv_label_create(ui_Q1P9HGSBCounter);
    lv_obj_set_width(ui_Q1P9HGSBCText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSBCText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1P9HGSBCText, 0);
    lv_obj_set_y(ui_Q1P9HGSBCText, -65);
    lv_obj_set_align(ui_Q1P9HGSBCText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSBCText, "Balls");
    lv_obj_remove_flag(ui_Q1P9HGSBCText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSBCText, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSBCText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSBCText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSBCPanel = lv_obj_create(ui_Q1P9HGSBCounter);
    lv_obj_set_width(ui_Q1P9HGSBCPanel, 100);
    lv_obj_set_height(ui_Q1P9HGSBCPanel, 100);
    lv_obj_set_x(ui_Q1P9HGSBCPanel, 0);
    lv_obj_set_y(ui_Q1P9HGSBCPanel, 55);
    lv_obj_set_align(ui_Q1P9HGSBCPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSBCPanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1P9HGSBCPanel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1P9HGSBCPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSBCPText = lv_label_create(ui_Q1P9HGSBCPanel);
    lv_obj_set_width(ui_Q1P9HGSBCPText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSBCPText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSBCPText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSBCPText, "2");
    lv_obj_remove_flag(ui_Q1P9HGSBCPText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSBCPText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSBCPText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSBCPText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPScoreboard = lv_image_create(ui_Q1P9HGScreen);
    lv_image_set_src(ui_Q1P9HGSPScoreboard, &ui_img_go_ball_750_x_415_png);
    lv_obj_set_width(ui_Q1P9HGSPScoreboard, LV_SIZE_CONTENT);   /// 768
    lv_obj_set_height(ui_Q1P9HGSPScoreboard, LV_SIZE_CONTENT);    /// 414
    lv_obj_set_align(ui_Q1P9HGSPScoreboard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSPScoreboard,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1P9HGSPSText = lv_label_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1P9HGSPSText, 0);
    lv_obj_set_y(ui_Q1P9HGSPSText, -121);
    lv_obj_set_align(ui_Q1P9HGSPSText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSText, "Player 1");
    lv_obj_remove_flag(ui_Q1P9HGSPSText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSText, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Q1P9HGSPSText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Q1P9HGSPSText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar3Text = lv_label_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1P9HGSPSPar3Text, -235);
    lv_obj_set_y(ui_Q1P9HGSPSPar3Text, -15);
    lv_obj_set_align(ui_Q1P9HGSPSPar3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar3Text, "3 Pts");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar3Text, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar4Text = lv_label_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1P9HGSPSPar4Text, 90);
    lv_obj_set_y(ui_Q1P9HGSPSPar4Text, -15);
    lv_obj_set_align(ui_Q1P9HGSPSPar4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar4Text, "4 Pts");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar4Text, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar5Text = lv_label_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1P9HGSPSPar5Text, -95);
    lv_obj_set_y(ui_Q1P9HGSPSPar5Text, 105);
    lv_obj_set_align(ui_Q1P9HGSPSPar5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar5Text, "5 Pts");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar5Text, lv_color_hex(0x00F46A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar3Panel = lv_obj_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar3Panel, 100);
    lv_obj_set_height(ui_Q1P9HGSPSPar3Panel, 100);
    lv_obj_set_x(ui_Q1P9HGSPSPar3Panel, -95);
    lv_obj_set_y(ui_Q1P9HGSPSPar3Panel, -15);
    lv_obj_set_align(ui_Q1P9HGSPSPar3Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSPSPar3Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1P9HGSPSPar3Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1P9HGSPSPar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar3PText = lv_label_create(ui_Q1P9HGSPSPar3Panel);
    lv_obj_set_width(ui_Q1P9HGSPSPar3PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar3PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSPSPar3PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar3PText, "2");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar3PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar3PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar3PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar3PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar4Panel = lv_obj_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar4Panel, 100);
    lv_obj_set_height(ui_Q1P9HGSPSPar4Panel, 100);
    lv_obj_set_x(ui_Q1P9HGSPSPar4Panel, 240);
    lv_obj_set_y(ui_Q1P9HGSPSPar4Panel, -15);
    lv_obj_set_align(ui_Q1P9HGSPSPar4Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSPSPar4Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1P9HGSPSPar4Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1P9HGSPSPar4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar4PText = lv_label_create(ui_Q1P9HGSPSPar4Panel);
    lv_obj_set_width(ui_Q1P9HGSPSPar4PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar4PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSPSPar4PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar4PText, "5");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar4PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar4PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar4PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar4PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar5Panel = lv_obj_create(ui_Q1P9HGSPScoreboard);
    lv_obj_set_width(ui_Q1P9HGSPSPar5Panel, 100);
    lv_obj_set_height(ui_Q1P9HGSPSPar5Panel, 100);
    lv_obj_set_x(ui_Q1P9HGSPSPar5Panel, 60);
    lv_obj_set_y(ui_Q1P9HGSPSPar5Panel, 105);
    lv_obj_set_align(ui_Q1P9HGSPSPar5Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Q1P9HGSPSPar5Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1P9HGSPSPar5Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1P9HGSPSPar5Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1P9HGSPSPar5PText = lv_label_create(ui_Q1P9HGSPSPar5Panel);
    lv_obj_set_width(ui_Q1P9HGSPSPar5PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1P9HGSPSPar5PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1P9HGSPSPar5PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1P9HGSPSPar5PText, "2");
    lv_obj_remove_flag(ui_Q1P9HGSPSPar5PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1P9HGSPSPar5PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1P9HGSPSPar5PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1P9HGSPSPar5PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Q1P9HGSMMBText, ui_event_Q1P9HGSMMBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1P9HGSMMButton, ui_event_Q1P9HGSMMButton, LV_EVENT_ALL, NULL);

}
