// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_Q1PHSScreen_screen_init(void)
{
    ui_Q1PHSScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Q1PHSScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Q1PHSScreen, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Q1PHSScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Q1PHSScreen, &ui_img_venice_18th_2047x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Q1PHSScreen, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Q1PHSScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Q1PHSScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1PHSHSLogo = lv_img_create(ui_Q1PHSScreen);
    lv_img_set_src(ui_Q1PHSHSLogo, &ui_img_studio_go_ball_logo_350x319_png);
    lv_obj_set_width(ui_Q1PHSHSLogo, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_Q1PHSHSLogo, LV_SIZE_CONTENT);    /// 319
    lv_obj_set_x(ui_Q1PHSHSLogo, 0);
    lv_obj_set_y(ui_Q1PHSHSLogo, -110);
    lv_obj_set_align(ui_Q1PHSHSLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Q1PHSHSLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1PHS9HButton = lv_img_create(ui_Q1PHSScreen);
    lv_img_set_src(ui_Q1PHS9HButton, &ui_img_go_ball_350x319_png);
    lv_obj_set_width(ui_Q1PHS9HButton, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_Q1PHS9HButton, LV_SIZE_CONTENT);    /// 319
    lv_obj_set_x(ui_Q1PHS9HButton, -350);
    lv_obj_set_y(ui_Q1PHS9HButton, 100);
    lv_obj_set_align(ui_Q1PHS9HButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Q1PHS9HButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHS9HButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1PHS9HBText = lv_label_create(ui_Q1PHS9HButton);
    lv_obj_set_width(ui_Q1PHS9HBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1PHS9HBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1PHS9HBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1PHS9HBText, "9\nHoles");
    lv_obj_add_flag(ui_Q1PHS9HBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHS9HBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1PHS9HBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1PHS9HBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Q1PHS9HBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Q1PHS9HBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Q1PHS9HBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1PHS9HBText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1PHS18HButton = lv_img_create(ui_Q1PHSScreen);
    lv_img_set_src(ui_Q1PHS18HButton, &ui_img_go_ball_350x319_png);
    lv_obj_set_width(ui_Q1PHS18HButton, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_Q1PHS18HButton, LV_SIZE_CONTENT);    /// 319
    lv_obj_set_x(ui_Q1PHS18HButton, 352);
    lv_obj_set_y(ui_Q1PHS18HButton, 100);
    lv_obj_set_align(ui_Q1PHS18HButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Q1PHS18HButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHS18HButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1PHS18HBText = lv_label_create(ui_Q1PHS18HButton);
    lv_obj_set_width(ui_Q1PHS18HBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1PHS18HBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1PHS18HBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1PHS18HBText, "18\nHoles");
    lv_obj_add_flag(ui_Q1PHS18HBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHS18HBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1PHS18HBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1PHS18HBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Q1PHS18HBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Q1PHS18HBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Q1PHS18HBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1PHS18HBText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1PHSFormat = lv_img_create(ui_Q1PHSScreen);
    lv_img_set_src(ui_Q1PHSFormat, &ui_img_go_ball_225x205_png);
    lv_obj_set_width(ui_Q1PHSFormat, LV_SIZE_CONTENT);   /// 225
    lv_obj_set_height(ui_Q1PHSFormat, LV_SIZE_CONTENT);    /// 205
    lv_obj_set_x(ui_Q1PHSFormat, -550);
    lv_obj_set_y(ui_Q1PHSFormat, -165);
    lv_obj_set_align(ui_Q1PHSFormat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Q1PHSFormat, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1PHSFText = lv_label_create(ui_Q1PHSFormat);
    lv_obj_set_width(ui_Q1PHSFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1PHSFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Q1PHSFText, -3);
    lv_obj_set_y(ui_Q1PHSFText, -6);
    lv_obj_set_align(ui_Q1PHSFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1PHSFText, "1P\nQUOTA");
    lv_obj_clear_flag(ui_Q1PHSFText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1PHSFText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1PHSFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Q1PHSFText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1PHSFText, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q1PHSBButton = lv_img_create(ui_Q1PHSScreen);
    lv_img_set_src(ui_Q1PHSBButton, &ui_img_go_ball_225x205_png);
    lv_obj_set_width(ui_Q1PHSBButton, LV_SIZE_CONTENT);   /// 225
    lv_obj_set_height(ui_Q1PHSBButton, LV_SIZE_CONTENT);    /// 205
    lv_obj_set_x(ui_Q1PHSBButton, 550);
    lv_obj_set_y(ui_Q1PHSBButton, -165);
    lv_obj_set_align(ui_Q1PHSBButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Q1PHSBButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHSBButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Q1PHSBBText = lv_label_create(ui_Q1PHSBButton);
    lv_obj_set_width(ui_Q1PHSBBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q1PHSBBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q1PHSBBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q1PHSBBText, "Back");
    lv_obj_add_flag(ui_Q1PHSBBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Q1PHSBBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q1PHSBBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q1PHSBBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Q1PHSBBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Q1PHSBBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q1PHSBBText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Q1PHS9HBText, ui_event_Q1PHS9HBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1PHS9HButton, ui_event_Q1PHS9HButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1PHS18HBText, ui_event_Q1PHS18HBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1PHS18HButton, ui_event_Q1PHS18HButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1PHSBBText, ui_event_Q1PHSBBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Q1PHSBButton, ui_event_Q1PHSBButton, LV_EVENT_ALL, NULL);

}
