// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_SP2P9HScorecard_screen_init(void)
{
    ui_SP2P9HScorecard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SP2P9HScorecard,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScorecard, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScorecard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SP2P9HScorecard, &ui_img_venice_18th_2560x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SP2P9HScorecard, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SP2P9HScorecard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SP2P9HScorecard, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScLogo = lv_image_create(ui_SP2P9HScorecard);
    lv_image_set_src(ui_SP2P9HScLogo, &ui_img_studio_go_ball_logo_350x319_png);
    lv_obj_set_width(ui_SP2P9HScLogo, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_SP2P9HScLogo, LV_SIZE_CONTENT);    /// 337
    lv_obj_set_x(ui_SP2P9HScLogo, 0);
    lv_obj_set_y(ui_SP2P9HScLogo, -145);
    lv_obj_set_align(ui_SP2P9HScLogo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_SP2P9HScMMButton = lv_image_create(ui_SP2P9HScorecard);
    lv_image_set_src(ui_SP2P9HScMMButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_SP2P9HScMMButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_SP2P9HScMMButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_SP2P9HScMMButton, -915);
    lv_obj_set_y(ui_SP2P9HScMMButton, -80);
    lv_obj_set_align(ui_SP2P9HScMMButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SP2P9HScMMButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SP2P9HScMMButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_SP2P9HScMMBText = lv_label_create(ui_SP2P9HScMMButton);
    lv_obj_set_width(ui_SP2P9HScMMBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScMMBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScMMBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScMMBText, "Main\nMenu");
    lv_obj_add_flag(ui_SP2P9HScMMBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SP2P9HScMMBText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScMMBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScMMBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SP2P9HScMMBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SP2P9HScMMBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SP2P9HScMMBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScMMBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScBButton = lv_image_create(ui_SP2P9HScorecard);
    lv_image_set_src(ui_SP2P9HScBButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_SP2P9HScBButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_SP2P9HScBButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_SP2P9HScBButton, 915);
    lv_obj_set_y(ui_SP2P9HScBButton, -80);
    lv_obj_set_align(ui_SP2P9HScBButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SP2P9HScBButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SP2P9HScBButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_SP2P9HScBBText = lv_label_create(ui_SP2P9HScBButton);
    lv_obj_set_width(ui_SP2P9HScBBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScBBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScBBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScBBText, "Back");
    lv_obj_add_flag(ui_SP2P9HScBBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SP2P9HScBBText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScBBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScBBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SP2P9HScBBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SP2P9HScBBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScBBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText, -468);
    lv_obj_set_y(ui_SP2P9HScHText, 70);
    lv_obj_set_align(ui_SP2P9HScHText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText, "Hole");
    lv_obj_remove_flag(ui_SP2P9HScHText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Text = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScP1Text, -525);
    lv_obj_set_y(ui_SP2P9HScP1Text, 155);
    lv_obj_set_align(ui_SP2P9HScP1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1Text, "Player 1");
    lv_obj_remove_flag(ui_SP2P9HScP1Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SP2P9HScP1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SP2P9HScP1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Text = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScP2Text, -525);
    lv_obj_set_y(ui_SP2P9HScP2Text, 260);
    lv_obj_set_align(ui_SP2P9HScP2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2Text, "Player 2");
    lv_obj_remove_flag(ui_SP2P9HScP2Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SP2P9HScP2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SP2P9HScP2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText1 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText1, -330);
    lv_obj_set_y(ui_SP2P9HScHText1, 70);
    lv_obj_set_align(ui_SP2P9HScHText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText1, "1");
    lv_obj_remove_flag(ui_SP2P9HScHText1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText1, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText2 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText2, -225);
    lv_obj_set_y(ui_SP2P9HScHText2, 70);
    lv_obj_set_align(ui_SP2P9HScHText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText2, "2");
    lv_obj_remove_flag(ui_SP2P9HScHText2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText2, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText3 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText3, -121);
    lv_obj_set_y(ui_SP2P9HScHText3, 70);
    lv_obj_set_align(ui_SP2P9HScHText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText3, "3");
    lv_obj_remove_flag(ui_SP2P9HScHText3,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText3, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText4 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText4, -16);
    lv_obj_set_y(ui_SP2P9HScHText4, 70);
    lv_obj_set_align(ui_SP2P9HScHText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText4, "4");
    lv_obj_remove_flag(ui_SP2P9HScHText4,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText4, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText5 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText5, 89);
    lv_obj_set_y(ui_SP2P9HScHText5, 70);
    lv_obj_set_align(ui_SP2P9HScHText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText5, "5");
    lv_obj_remove_flag(ui_SP2P9HScHText5,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText5, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText6 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText6, 194);
    lv_obj_set_y(ui_SP2P9HScHText6, 70);
    lv_obj_set_align(ui_SP2P9HScHText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText6, "6");
    lv_obj_remove_flag(ui_SP2P9HScHText6,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText6, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText7 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText7, 299);
    lv_obj_set_y(ui_SP2P9HScHText7, 70);
    lv_obj_set_align(ui_SP2P9HScHText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText7, "7");
    lv_obj_remove_flag(ui_SP2P9HScHText7,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText7, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText8 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText8, 404);
    lv_obj_set_y(ui_SP2P9HScHText8, 70);
    lv_obj_set_align(ui_SP2P9HScHText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText8, "8");
    lv_obj_remove_flag(ui_SP2P9HScHText8,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText8, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHText9 = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHText9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHText9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHText9, 509);
    lv_obj_set_y(ui_SP2P9HScHText9, 70);
    lv_obj_set_align(ui_SP2P9HScHText9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHText9, "9");
    lv_obj_remove_flag(ui_SP2P9HScHText9,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHText9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHText9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHText9, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScHTextF = lv_label_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScHTextF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScHTextF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScHTextF, 614);
    lv_obj_set_y(ui_SP2P9HScHTextF, 70);
    lv_obj_set_align(ui_SP2P9HScHTextF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScHTextF, "F");
    lv_obj_remove_flag(ui_SP2P9HScHTextF,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScHTextF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScHTextF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScHTextF, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox1 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox1, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox1, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox1, -330);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox1, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox1, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S1Text = lv_label_create(ui_SP2P9HScP1Spinbox1);
    lv_obj_set_width(ui_SP2P9HScP1S1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S1Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S1Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S1Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox2 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox2, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox2, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox2, -225);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox2, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox2, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S2Text = lv_label_create(ui_SP2P9HScP1Spinbox2);
    lv_obj_set_width(ui_SP2P9HScP1S2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S2Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S2Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S2Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox3 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox3, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox3, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox3, -121);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox3, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox3, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S3Text = lv_label_create(ui_SP2P9HScP1Spinbox3);
    lv_obj_set_width(ui_SP2P9HScP1S3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S3Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox4 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox4, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox4, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox4, -16);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox4, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox4, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S4Text = lv_label_create(ui_SP2P9HScP1Spinbox4);
    lv_obj_set_width(ui_SP2P9HScP1S4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S4Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox5 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox5, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox5, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox5, 89);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox5, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox5,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox5, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S5Text = lv_label_create(ui_SP2P9HScP1Spinbox5);
    lv_obj_set_width(ui_SP2P9HScP1S5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S5Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox6 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox6, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox6, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox6, 194);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox6, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox6,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox6, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S6Text = lv_label_create(ui_SP2P9HScP1Spinbox6);
    lv_obj_set_width(ui_SP2P9HScP1S6Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S6Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S6Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S6Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S6Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S6Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S6Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S6Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox7 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox7, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox7, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox7, 299);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox7, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox7,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox7, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S7Text = lv_label_create(ui_SP2P9HScP1Spinbox7);
    lv_obj_set_width(ui_SP2P9HScP1S7Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S7Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S7Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S7Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S7Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S7Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S7Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S7Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox8 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox8, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox8, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox8, 404);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox8, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox8, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S8Text = lv_label_create(ui_SP2P9HScP1Spinbox8);
    lv_obj_set_width(ui_SP2P9HScP1S8Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S8Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S8Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S8Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S8Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S8Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S8Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S8Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1Spinbox9 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1Spinbox9, 100);
    lv_obj_set_height(ui_SP2P9HScP1Spinbox9, 100);
    lv_obj_set_x(ui_SP2P9HScP1Spinbox9, 509);
    lv_obj_set_y(ui_SP2P9HScP1Spinbox9, 155);
    lv_obj_set_align(ui_SP2P9HScP1Spinbox9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1Spinbox9,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1Spinbox9, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1Spinbox9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1S9Text = lv_label_create(ui_SP2P9HScP1Spinbox9);
    lv_obj_set_width(ui_SP2P9HScP1S9Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1S9Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1S9Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1S9Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1S9Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1S9Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1S9Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1S9Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1SpinboxF = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP1SpinboxF, 100);
    lv_obj_set_height(ui_SP2P9HScP1SpinboxF, 100);
    lv_obj_set_x(ui_SP2P9HScP1SpinboxF, 614);
    lv_obj_set_y(ui_SP2P9HScP1SpinboxF, 155);
    lv_obj_set_align(ui_SP2P9HScP1SpinboxF, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP1SpinboxF,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP1SpinboxF, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP1SpinboxF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP1SFText = lv_label_create(ui_SP2P9HScP1SpinboxF);
    lv_obj_set_width(ui_SP2P9HScP1SFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP1SFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP1SFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP1SFText, "0");
    lv_obj_remove_flag(ui_SP2P9HScP1SFText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP1SFText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP1SFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP1SFText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox1 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox1, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox1, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox1, -330);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox1, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox1, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S1Text = lv_label_create(ui_SP2P9HScP2Spinbox1);
    lv_obj_set_width(ui_SP2P9HScP2S1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S1Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S1Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S1Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox2 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox2, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox2, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox2, -225);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox2, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox2, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S2Text = lv_label_create(ui_SP2P9HScP2Spinbox2);
    lv_obj_set_width(ui_SP2P9HScP2S2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S2Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S2Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S2Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox3 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox3, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox3, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox3, -121);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox3, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox3, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S3Text = lv_label_create(ui_SP2P9HScP2Spinbox3);
    lv_obj_set_width(ui_SP2P9HScP2S3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S3Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox4 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox4, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox4, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox4, -16);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox4, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox4, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S4Text = lv_label_create(ui_SP2P9HScP2Spinbox4);
    lv_obj_set_width(ui_SP2P9HScP2S4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S4Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox5 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox5, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox5, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox5, 89);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox5, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox5,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox5, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S5Text = lv_label_create(ui_SP2P9HScP2Spinbox5);
    lv_obj_set_width(ui_SP2P9HScP2S5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S5Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox6 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox6, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox6, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox6, 194);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox6, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox6,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox6, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S6Text = lv_label_create(ui_SP2P9HScP2Spinbox6);
    lv_obj_set_width(ui_SP2P9HScP2S6Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S6Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S6Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S6Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S6Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S6Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S6Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S6Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox7 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox7, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox7, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox7, 299);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox7, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox7,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox7, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S7Text = lv_label_create(ui_SP2P9HScP2Spinbox7);
    lv_obj_set_width(ui_SP2P9HScP2S7Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S7Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S7Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S7Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S7Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S7Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S7Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S7Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox8 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox8, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox8, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox8, 404);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox8, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox8, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S8Text = lv_label_create(ui_SP2P9HScP2Spinbox8);
    lv_obj_set_width(ui_SP2P9HScP2S8Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S8Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S8Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S8Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S8Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S8Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S8Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S8Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2Spinbox9 = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2Spinbox9, 100);
    lv_obj_set_height(ui_SP2P9HScP2Spinbox9, 100);
    lv_obj_set_x(ui_SP2P9HScP2Spinbox9, 509);
    lv_obj_set_y(ui_SP2P9HScP2Spinbox9, 260);
    lv_obj_set_align(ui_SP2P9HScP2Spinbox9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2Spinbox9,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2Spinbox9, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2Spinbox9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2S9Text = lv_label_create(ui_SP2P9HScP2Spinbox9);
    lv_obj_set_width(ui_SP2P9HScP2S9Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2S9Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SP2P9HScP2S9Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2S9Text, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2S9Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2S9Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2S9Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2S9Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2SpinboxF = lv_obj_create(ui_SP2P9HScorecard);
    lv_obj_set_width(ui_SP2P9HScP2SpinboxF, 100);
    lv_obj_set_height(ui_SP2P9HScP2SpinboxF, 100);
    lv_obj_set_x(ui_SP2P9HScP2SpinboxF, 614);
    lv_obj_set_y(ui_SP2P9HScP2SpinboxF, 260);
    lv_obj_set_align(ui_SP2P9HScP2SpinboxF, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SP2P9HScP2SpinboxF,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SP2P9HScP2SpinboxF, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SP2P9HScP2SpinboxF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2P9HScP2SFText = lv_label_create(ui_SP2P9HScP2SpinboxF);
    lv_obj_set_width(ui_SP2P9HScP2SFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2P9HScP2SFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2P9HScP2SFText, 1);
    lv_obj_set_y(ui_SP2P9HScP2SFText, 0);
    lv_obj_set_align(ui_SP2P9HScP2SFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2P9HScP2SFText, "0");
    lv_obj_remove_flag(ui_SP2P9HScP2SFText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SP2P9HScP2SFText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2P9HScP2SFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SP2P9HScP2SFText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SP2P9HScMMBText, ui_event_SP2P9HScMMBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SP2P9HScMMButton, ui_event_SP2P9HScMMButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SP2P9HScBBText, ui_event_SP2P9HScBBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SP2P9HScBButton, ui_event_SP2P9HScBButton, LV_EVENT_ALL, NULL);

}
