// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_VQPSScreen_screen_init(void)
{
    ui_VQPSScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_VQPSScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_VQPSScreen, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQPSScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_VQPSScreen, &ui_img_venice_18th_2560x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VQPSScreen, lv_color_hex(0x00EE49), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VQPSScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VQPSScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSSLogo = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSSLogo, &ui_img_studio_go_ball_logo_225x205_png);
    lv_obj_set_width(ui_VQPSSLogo, LV_SIZE_CONTENT);   /// 225
    lv_obj_set_height(ui_VQPSSLogo, LV_SIZE_CONTENT);    /// 205
    lv_obj_set_x(ui_VQPSSLogo, 0);
    lv_obj_set_y(ui_VQPSSLogo, -195);
    lv_obj_set_align(ui_VQPSSLogo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQPSSLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSSFormat = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSSFormat, &ui_img_go_ball_225x205_png);
    lv_obj_set_width(ui_VQPSSFormat, LV_SIZE_CONTENT);   /// 225
    lv_obj_set_height(ui_VQPSSFormat, LV_SIZE_CONTENT);    /// 205
    lv_obj_set_x(ui_VQPSSFormat, -540);
    lv_obj_set_y(ui_VQPSSFormat, -195);
    lv_obj_set_align(ui_VQPSSFormat, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQPSSFormat, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSSFText = lv_label_create(ui_VQPSSFormat);
    lv_obj_set_width(ui_VQPSSFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSSFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSSFText, 4);
    lv_obj_set_y(ui_VQPSSFText, 2);
    lv_obj_set_align(ui_VQPSSFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSSFText, "Vegas\nQuota");
    lv_obj_remove_flag(ui_VQPSSFText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSSFText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSSFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VQPSSFText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSSFText, &ui_font_Unitblock_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSSBButton = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSSBButton, &ui_img_go_ball_225x205_png);
    lv_obj_set_width(ui_VQPSSBButton, LV_SIZE_CONTENT);   /// 225
    lv_obj_set_height(ui_VQPSSBButton, LV_SIZE_CONTENT);    /// 205
    lv_obj_set_x(ui_VQPSSBButton, 540);
    lv_obj_set_y(ui_VQPSSBButton, -195);
    lv_obj_set_align(ui_VQPSSBButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQPSSBButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSSBButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSSBBText = lv_label_create(ui_VQPSSBButton);
    lv_obj_set_width(ui_VQPSSBBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSSBBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSSBBText, 4);
    lv_obj_set_y(ui_VQPSSBBText, -3);
    lv_obj_set_align(ui_VQPSSBBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSSBBText, "Back");
    lv_obj_add_flag(ui_VQPSSBBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSSBBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSSBBText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSSBBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQPSSBBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQPSSBBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSSBBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSS1PButton = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSS1PButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_VQPSS1PButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_VQPSS1PButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_VQPSS1PButton, -800);
    lv_obj_set_y(ui_VQPSS1PButton, 85);
    lv_obj_set_align(ui_VQPSS1PButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQPSS1PButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS1PButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSS1PBText = lv_label_create(ui_VQPSS1PButton);
    lv_obj_set_width(ui_VQPSS1PBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSS1PBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSS1PBText, 3);
    lv_obj_set_y(ui_VQPSS1PBText, 0);
    lv_obj_set_align(ui_VQPSS1PBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSS1PBText, "1 Player");
    lv_obj_add_flag(ui_VQPSS1PBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS1PBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSS1PBText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSS1PBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQPSS1PBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQPSS1PBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSS1PBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSS2PButton = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSS2PButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_VQPSS2PButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_VQPSS2PButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_VQPSS2PButton, -265);
    lv_obj_set_y(ui_VQPSS2PButton, 85);
    lv_obj_set_align(ui_VQPSS2PButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQPSS2PButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS2PButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSS2PBText = lv_label_create(ui_VQPSS2PButton);
    lv_obj_set_width(ui_VQPSS2PBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSS2PBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSS2PBText, 4);
    lv_obj_set_y(ui_VQPSS2PBText, 0);
    lv_obj_set_align(ui_VQPSS2PBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSS2PBText, "2 Player");
    lv_obj_add_flag(ui_VQPSS2PBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS2PBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSS2PBText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSS2PBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQPSS2PBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQPSS2PBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSS2PBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSS3PButton = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSS3PButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_VQPSS3PButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_VQPSS3PButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_VQPSS3PButton, 265);
    lv_obj_set_y(ui_VQPSS3PButton, 85);
    lv_obj_set_align(ui_VQPSS3PButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQPSS3PButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS3PButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSS3PBText = lv_label_create(ui_VQPSS3PButton);
    lv_obj_set_width(ui_VQPSS3PBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSS3PBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSS3PBText, 3);
    lv_obj_set_y(ui_VQPSS3PBText, 0);
    lv_obj_set_align(ui_VQPSS3PBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSS3PBText, "3 Player");
    lv_obj_add_flag(ui_VQPSS3PBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS3PBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSS3PBText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSS3PBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQPSS3PBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQPSS3PBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSS3PBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQPSS4PButton = lv_image_create(ui_VQPSScreen);
    lv_image_set_src(ui_VQPSS4PButton, &ui_img_go_ball_450x431_png);
    lv_obj_set_width(ui_VQPSS4PButton, LV_SIZE_CONTENT);   /// 450
    lv_obj_set_height(ui_VQPSS4PButton, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_VQPSS4PButton, 800);
    lv_obj_set_y(ui_VQPSS4PButton, 85);
    lv_obj_set_align(ui_VQPSS4PButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQPSS4PButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS4PButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQPSS4PBText = lv_label_create(ui_VQPSS4PButton);
    lv_obj_set_width(ui_VQPSS4PBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQPSS4PBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQPSS4PBText, 4);
    lv_obj_set_y(ui_VQPSS4PBText, 0);
    lv_obj_set_align(ui_VQPSS4PBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQPSS4PBText, "4 Player");
    lv_obj_add_flag(ui_VQPSS4PBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQPSS4PBText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQPSS4PBText, lv_color_hex(0x00F64A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQPSS4PBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQPSS4PBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQPSS4PBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQPSS4PBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VQPSSBBText, ui_event_VQPSSBBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSSBButton, ui_event_VQPSSBButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS1PBText, ui_event_VQPSS1PBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS1PButton, ui_event_VQPSS1PButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS2PBText, ui_event_VQPSS2PBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS2PButton, ui_event_VQPSS2PButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS3PBText, ui_event_VQPSS3PBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS3PButton, ui_event_VQPSS3PButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS4PBText, ui_event_VQPSS4PBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQPSS4PButton, ui_event_VQPSS4PButton, LV_EVENT_ALL, NULL);

}
