// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "../ui.h"

void ui_VQ3P18HGScreen_screen_init(void)
{
    ui_VQ3P18HGScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_VQ3P18HGScreen,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGScreen, lv_color_hex(0xACB6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_VQ3P18HGScreen, &ui_img_venice_18th_2560x720_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VQ3P18HGScreen, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VQ3P18HGScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VQ3P18HGScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSLogo = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSLogo, &ui_img_studio_go_ball_logo_300x273_png);
    lv_obj_set_width(ui_VQ3P18HGSLogo, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_VQ3P18HGSLogo, LV_SIZE_CONTENT);    /// 289
    lv_obj_set_x(ui_VQ3P18HGSLogo, -375);
    lv_obj_set_y(ui_VQ3P18HGSLogo, -182);
    lv_obj_set_align(ui_VQ3P18HGSLogo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSLogo,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSFormat = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSFormat, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_VQ3P18HGSFormat, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_VQ3P18HGSFormat, LV_SIZE_CONTENT);    /// 287
    lv_obj_set_x(ui_VQ3P18HGSFormat, 1104);
    lv_obj_set_y(ui_VQ3P18HGSFormat, -198);
    lv_obj_set_align(ui_VQ3P18HGSFormat, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSFormat,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSFText = lv_label_create(ui_VQ3P18HGSFormat);
    lv_obj_set_width(ui_VQ3P18HGSFText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSFText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSFText, 0);
    lv_obj_set_y(ui_VQ3P18HGSFText, 4);
    lv_obj_set_align(ui_VQ3P18HGSFText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSFText, "3P\nVegas\nQuota\n18H");
    lv_obj_remove_flag(ui_VQ3P18HGSFText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSFText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSFText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VQ3P18HGSFText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSFText, &ui_font_Unitblock_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSMMButton = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSMMButton, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_VQ3P18HGSMMButton, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_VQ3P18HGSMMButton, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_VQ3P18HGSMMButton, -1104);
    lv_obj_set_y(ui_VQ3P18HGSMMButton, -198);
    lv_obj_set_align(ui_VQ3P18HGSMMButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQ3P18HGSMMButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQ3P18HGSMMButton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSMMBText = lv_label_create(ui_VQ3P18HGSMMButton);
    lv_obj_set_width(ui_VQ3P18HGSMMBText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSMMBText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSMMBText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSMMBText, "Main\nMenu");
    lv_obj_add_flag(ui_VQ3P18HGSMMBText, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VQ3P18HGSMMBText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSMMBText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSMMBText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_VQ3P18HGSMMBText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VQ3P18HGSMMBText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VQ3P18HGSMMBText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSMMBText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSBCounter = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSBCounter, &ui_img_go_ball_300x273_png);
    lv_obj_set_width(ui_VQ3P18HGSBCounter, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_VQ3P18HGSBCounter, LV_SIZE_CONTENT);    /// 287
    lv_obj_set_x(ui_VQ3P18HGSBCounter, 375);
    lv_obj_set_y(ui_VQ3P18HGSBCounter, -182);
    lv_obj_set_align(ui_VQ3P18HGSBCounter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSBCounter,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSBCText = lv_label_create(ui_VQ3P18HGSBCounter);
    lv_obj_set_width(ui_VQ3P18HGSBCText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSBCText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSBCText, 0);
    lv_obj_set_y(ui_VQ3P18HGSBCText, -65);
    lv_obj_set_align(ui_VQ3P18HGSBCText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSBCText, "Balls");
    lv_obj_remove_flag(ui_VQ3P18HGSBCText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSBCText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSBCText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSBCText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSBCPanel = lv_obj_create(ui_VQ3P18HGSBCounter);
    lv_obj_set_width(ui_VQ3P18HGSBCPanel, 100);
    lv_obj_set_height(ui_VQ3P18HGSBCPanel, 100);
    lv_obj_set_x(ui_VQ3P18HGSBCPanel, 0);
    lv_obj_set_y(ui_VQ3P18HGSBCPanel, 50);
    lv_obj_set_align(ui_VQ3P18HGSBCPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSBCPanel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSBCPanel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSBCPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Q3P9HGSBCPText2 = lv_label_create(ui_VQ3P18HGSBCPanel);
    lv_obj_set_width(ui_Q3P9HGSBCPText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Q3P9HGSBCPText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Q3P9HGSBCPText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Q3P9HGSBCPText2, "2");
    lv_obj_remove_flag(ui_Q3P9HGSBCPText2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Q3P9HGSBCPText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Q3P9HGSBCPText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Q3P9HGSBCPText2, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1Scoreboard = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSP1Scoreboard, &ui_img_go_ball_750_x_415_png);
    lv_obj_set_width(ui_VQ3P18HGSP1Scoreboard, LV_SIZE_CONTENT);   /// 768
    lv_obj_set_height(ui_VQ3P18HGSP1Scoreboard, LV_SIZE_CONTENT);    /// 414
    lv_obj_set_x(ui_VQ3P18HGSP1Scoreboard, -755);
    lv_obj_set_y(ui_VQ3P18HGSP1Scoreboard, 130);
    lv_obj_set_align(ui_VQ3P18HGSP1Scoreboard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP1Scoreboard,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP1SText = lv_label_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP1SText, -62);
    lv_obj_set_y(ui_VQ3P18HGSP1SText, -121);
    lv_obj_set_align(ui_VQ3P18HGSP1SText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SText, "Player 1");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VQ3P18HGSP1SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VQ3P18HGSP1SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar3Text = lv_label_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP1SPar3Text, -235);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar3Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar3Text, "3 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar3Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar4Text = lv_label_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP1SPar4Text, 90);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar4Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar4Text, "4 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar4Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar5Text = lv_label_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP1SPar5Text, -95);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar5Text, 105);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar5Text, "5 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar5Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar3Panel = lv_obj_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar3Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP1SPar3Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP1SPar3Panel, -95);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar3Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar3Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar3Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP1SPar3Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP1SPar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar3PText = lv_label_create(ui_VQ3P18HGSP1SPar3Panel);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar3PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar3PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP1SPar3PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar3PText, "4");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar3PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar3PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar3PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar3PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar4Panel = lv_obj_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar4Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP1SPar4Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP1SPar4Panel, 240);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar4Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar4Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar4Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP1SPar4Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP1SPar4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar4PText = lv_label_create(ui_VQ3P18HGSP1SPar4Panel);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar4PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar4PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP1SPar4PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar4PText, "10");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar4PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar4PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar4PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar4PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar5Panel = lv_obj_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar5Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP1SPar5Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP1SPar5Panel, 60);
    lv_obj_set_y(ui_VQ3P18HGSP1SPar5Panel, 105);
    lv_obj_set_align(ui_VQ3P18HGSP1SPar5Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar5Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP1SPar5Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP1SPar5Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SPar5PText = lv_label_create(ui_VQ3P18HGSP1SPar5Panel);
    lv_obj_set_width(ui_VQ3P18HGSP1SPar5PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1SPar5PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP1SPar5PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1SPar5PText, "4");
    lv_obj_remove_flag(ui_VQ3P18HGSP1SPar5PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1SPar5PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1SPar5PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1SPar5PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1SCrown = lv_image_create(ui_VQ3P18HGSP1Scoreboard);
    lv_image_set_src(ui_VQ3P18HGSP1SCrown, &ui_img_crown_resized_png);
    lv_obj_set_width(ui_VQ3P18HGSP1SCrown, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_VQ3P18HGSP1SCrown, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_VQ3P18HGSP1SCrown, -225);
    lv_obj_set_y(ui_VQ3P18HGSP1SCrown, -121);
    lv_obj_set_align(ui_VQ3P18HGSP1SCrown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQ3P18HGSP1SCrown, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_VQ3P18HGSP1SCrown,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP1Score = lv_obj_create(ui_VQ3P18HGSP1Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP1Score, 100);
    lv_obj_set_height(ui_VQ3P18HGSP1Score, 75);
    lv_obj_set_x(ui_VQ3P18HGSP1Score, 125);
    lv_obj_set_y(ui_VQ3P18HGSP1Score, -121);
    lv_obj_set_align(ui_VQ3P18HGSP1Score, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP1Score,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP1Score, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP1Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP1ScText = lv_label_create(ui_VQ3P18HGSP1Score);
    lv_obj_set_width(ui_VQ3P18HGSP1ScText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP1ScText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP1ScText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP1ScText, "0");
    lv_obj_remove_flag(ui_VQ3P18HGSP1ScText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP1ScText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP1ScText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP1ScText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2Scoreboard = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSP2Scoreboard, &ui_img_go_ball_750_x_415_png);
    lv_obj_set_width(ui_VQ3P18HGSP2Scoreboard, LV_SIZE_CONTENT);   /// 768
    lv_obj_set_height(ui_VQ3P18HGSP2Scoreboard, LV_SIZE_CONTENT);    /// 414
    lv_obj_set_x(ui_VQ3P18HGSP2Scoreboard, 0);
    lv_obj_set_y(ui_VQ3P18HGSP2Scoreboard, 130);
    lv_obj_set_align(ui_VQ3P18HGSP2Scoreboard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP2Scoreboard,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP2SText = lv_label_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP2SText, -62);
    lv_obj_set_y(ui_VQ3P18HGSP2SText, -121);
    lv_obj_set_align(ui_VQ3P18HGSP2SText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SText, "Player 2");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VQ3P18HGSP2SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VQ3P18HGSP2SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar3Text = lv_label_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP2SPar3Text, -235);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar3Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar3Text, "3 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar3Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar4Text = lv_label_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP2SPar4Text, 90);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar4Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar4Text, "4 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar4Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar5Text = lv_label_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP2SPar5Text, -95);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar5Text, 105);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar5Text, "5 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar5Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar3Panel = lv_obj_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar3Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP2SPar3Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP2SPar3Panel, -95);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar3Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar3Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar3Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP2SPar3Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP2SPar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar3PText = lv_label_create(ui_VQ3P18HGSP2SPar3Panel);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar3PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar3PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP2SPar3PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar3PText, "4");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar3PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar3PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar3PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar3PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar4Panel = lv_obj_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar4Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP2SPar4Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP2SPar4Panel, 240);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar4Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar4Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar4Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP2SPar4Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP2SPar4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar4PText = lv_label_create(ui_VQ3P18HGSP2SPar4Panel);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar4PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar4PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP2SPar4PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar4PText, "10");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar4PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar4PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar4PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar4PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar5Panel = lv_obj_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar5Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP2SPar5Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP2SPar5Panel, 60);
    lv_obj_set_y(ui_VQ3P18HGSP2SPar5Panel, 105);
    lv_obj_set_align(ui_VQ3P18HGSP2SPar5Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar5Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP2SPar5Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP2SPar5Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SPar5PText = lv_label_create(ui_VQ3P18HGSP2SPar5Panel);
    lv_obj_set_width(ui_VQ3P18HGSP2SPar5PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2SPar5PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP2SPar5PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2SPar5PText, "4");
    lv_obj_remove_flag(ui_VQ3P18HGSP2SPar5PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2SPar5PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2SPar5PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2SPar5PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2SCrown = lv_image_create(ui_VQ3P18HGSP2Scoreboard);
    lv_image_set_src(ui_VQ3P18HGSP2SCrown, &ui_img_crown_resized_png);
    lv_obj_set_width(ui_VQ3P18HGSP2SCrown, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_VQ3P18HGSP2SCrown, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_VQ3P18HGSP2SCrown, -225);
    lv_obj_set_y(ui_VQ3P18HGSP2SCrown, -121);
    lv_obj_set_align(ui_VQ3P18HGSP2SCrown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQ3P18HGSP2SCrown, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_VQ3P18HGSP2SCrown,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP2Score = lv_obj_create(ui_VQ3P18HGSP2Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP2Score, 100);
    lv_obj_set_height(ui_VQ3P18HGSP2Score, 75);
    lv_obj_set_x(ui_VQ3P18HGSP2Score, 125);
    lv_obj_set_y(ui_VQ3P18HGSP2Score, -121);
    lv_obj_set_align(ui_VQ3P18HGSP2Score, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP2Score,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP2Score, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP2Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP2ScText = lv_label_create(ui_VQ3P18HGSP2Score);
    lv_obj_set_width(ui_VQ3P18HGSP2ScText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP2ScText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP2ScText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP2ScText, "0");
    lv_obj_remove_flag(ui_VQ3P18HGSP2ScText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP2ScText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP2ScText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP2ScText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3Scoreboard = lv_image_create(ui_VQ3P18HGScreen);
    lv_image_set_src(ui_VQ3P18HGSP3Scoreboard, &ui_img_go_ball_750_x_415_png);
    lv_obj_set_width(ui_VQ3P18HGSP3Scoreboard, LV_SIZE_CONTENT);   /// 768
    lv_obj_set_height(ui_VQ3P18HGSP3Scoreboard, LV_SIZE_CONTENT);    /// 414
    lv_obj_set_x(ui_VQ3P18HGSP3Scoreboard, 755);
    lv_obj_set_y(ui_VQ3P18HGSP3Scoreboard, 130);
    lv_obj_set_align(ui_VQ3P18HGSP3Scoreboard, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP3Scoreboard,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP3SText = lv_label_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP3SText, -62);
    lv_obj_set_y(ui_VQ3P18HGSP3SText, -121);
    lv_obj_set_align(ui_VQ3P18HGSP3SText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SText, "Player 3");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VQ3P18HGSP3SText, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VQ3P18HGSP3SText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar3Text = lv_label_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar3Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar3Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP3SPar3Text, -235);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar3Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar3Text, "3 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar3Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar3Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar3Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar4Text = lv_label_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar4Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar4Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP3SPar4Text, 90);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar4Text, -15);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar4Text, "4 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar4Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar4Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar4Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar5Text = lv_label_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar5Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar5Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VQ3P18HGSP3SPar5Text, -95);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar5Text, 105);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar5Text, "5 Pts");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar5Text,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar5Text, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar5Text, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar3Panel = lv_obj_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar3Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP3SPar3Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP3SPar3Panel, -95);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar3Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar3Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar3Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP3SPar3Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP3SPar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar3PText = lv_label_create(ui_VQ3P18HGSP3SPar3Panel);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar3PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar3PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP3SPar3PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar3PText, "2");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar3PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar3PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar3PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar3PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar4Panel = lv_obj_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar4Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP3SPar4Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP3SPar4Panel, 240);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar4Panel, -15);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar4Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar4Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP3SPar4Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP3SPar4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar4PText = lv_label_create(ui_VQ3P18HGSP3SPar4Panel);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar4PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar4PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP3SPar4PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar4PText, "5");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar4PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar4PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar4PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar4PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar5Panel = lv_obj_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar5Panel, 100);
    lv_obj_set_height(ui_VQ3P18HGSP3SPar5Panel, 100);
    lv_obj_set_x(ui_VQ3P18HGSP3SPar5Panel, 60);
    lv_obj_set_y(ui_VQ3P18HGSP3SPar5Panel, 105);
    lv_obj_set_align(ui_VQ3P18HGSP3SPar5Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar5Panel,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP3SPar5Panel, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP3SPar5Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SPar5PText = lv_label_create(ui_VQ3P18HGSP3SPar5Panel);
    lv_obj_set_width(ui_VQ3P18HGSP3SPar5PText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3SPar5PText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP3SPar5PText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3SPar5PText, "2");
    lv_obj_remove_flag(ui_VQ3P18HGSP3SPar5PText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3SPar5PText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3SPar5PText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3SPar5PText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3SCrown = lv_image_create(ui_VQ3P18HGSP3Scoreboard);
    lv_image_set_src(ui_VQ3P18HGSP3SCrown, &ui_img_crown_resized_png);
    lv_obj_set_width(ui_VQ3P18HGSP3SCrown, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_VQ3P18HGSP3SCrown, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_VQ3P18HGSP3SCrown, -225);
    lv_obj_set_y(ui_VQ3P18HGSP3SCrown, -121);
    lv_obj_set_align(ui_VQ3P18HGSP3SCrown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VQ3P18HGSP3SCrown, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_VQ3P18HGSP3SCrown,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_VQ3P18HGSP3Score = lv_obj_create(ui_VQ3P18HGSP3Scoreboard);
    lv_obj_set_width(ui_VQ3P18HGSP3Score, 100);
    lv_obj_set_height(ui_VQ3P18HGSP3Score, 75);
    lv_obj_set_x(ui_VQ3P18HGSP3Score, 125);
    lv_obj_set_y(ui_VQ3P18HGSP3Score, -121);
    lv_obj_set_align(ui_VQ3P18HGSP3Score, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VQ3P18HGSP3Score,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_VQ3P18HGSP3Score, lv_color_hex(0x5AB66A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VQ3P18HGSP3Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VQ3P18HGSP3ScText = lv_label_create(ui_VQ3P18HGSP3Score);
    lv_obj_set_width(ui_VQ3P18HGSP3ScText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VQ3P18HGSP3ScText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VQ3P18HGSP3ScText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VQ3P18HGSP3ScText, "0");
    lv_obj_remove_flag(ui_VQ3P18HGSP3ScText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_VQ3P18HGSP3ScText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VQ3P18HGSP3ScText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VQ3P18HGSP3ScText, &ui_font_Unitblock_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VQ3P18HGSMMBText, ui_event_VQ3P18HGSMMBText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VQ3P18HGSMMButton, ui_event_VQ3P18HGSMMButton, LV_EVENT_ALL, NULL);

}
