// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Go Ball Raspbery PI

#include <wiringPi.h>
#include "ui.h"
void Player1Score(lv_event_t * e)
{	
}

void HoleCounterData(lv_event_t * e)
{	
}

void BallCounterData(lv_event_t * e)
{	
}
