// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Go Ball Raspbery PI

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Green[2] = {0x5AB66A, 0x5AB66A};
const ui_theme_variable_t _ui_theme_alpha_Green[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Grey[2] = {0xACB6BD, 0xACB6BD};
const ui_theme_variable_t _ui_theme_alpha_Grey[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

